<a href="https://colab.research.google.com/github/Olena-24/Science-HW-1/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np


*1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.*


In [ ]:
a = np.arange(1, 11)
print("Массив с помощью np.arange:", a)

#или другой способ

b = np.linspace(1, 10, num=10, dtype=int)
print("Массив с помощью np.linspace:", b)

Массив с помощью np.arange: [ 1  2  3  4  5  6  7  8  9 10]
Массив с помощью np.linspace: [ 1  2  3  4  5  6  7  8  9 10]


*2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.*

In [ ]:
zero_matrix = np.zeros((3, 3))
print("Матрица заполненная нулями:")
print(zero_matrix)

Матрица заполненная нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


*3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.*

In [ ]:
random_matrix = np.random.randint(1, 11, (5, 5))
print("Сгенерированная матрица:")
print(random_matrix)

Сгенерированная матрица:
[[ 8  2  3  2  3]
 [ 1  4  1  1  8]
 [ 5  4 10  5  3]
 [ 9  7  7  1  5]
 [ 3  6 10  7  3]]


*4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.*

In [ ]:

random_matrix = np.random.random((4, 4))
print("Сгенерированная матрица:")
print(random_matrix)

Сгенерированная матрица:
[[0.97140344 0.12542556 0.5827622  0.77478518]
 [0.050959   0.98861449 0.58900053 0.02900193]
 [0.52806561 0.77411722 0.17831647 0.19861356]
 [0.06893199 0.64007925 0.71815777 0.37576772]]


*5. Cтворіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.*

In [ ]:
array1 = np.random.randint(1, 11, size = 5)
array2 = np.random.randint(1, 11, size = 5)
product_result = array1 * array2
sum_result = array1 + array2
difference_result = array1 - array2

print("Массив array1:", array1)
print("Массив array2:", array2)
print("Результат умножения:", product_result)
print("Результат сложения:", sum_result)
print("Результат вычитания:", difference_result)

Массив array1: [ 2 10  9  1  6]
Массив array2: [ 7  4  8 10  8]
Результат умножения: [14 40 72 10 48]
Результат сложения: [ 9 14 17 11 14]
Результат вычитания: [-5  6  1 -9 -2]


*6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.*

In [ ]:
vector1 = np.random.randint(1, 100, size=7)
vector2 = np.random.randint(1, 100, size=7)
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Скалярное произведение:", np.dot(vector1, vector2))

Вектор 1: [39 44 22 77 90 21 20]
Вектор 2: [90 11 66 27 98 84 59]
Скалярный добуток: 19289


*7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.*

In [ ]:
rng = np.random.default_rng()
matrix1 = rng.integers(1, 11 , size = (2, 2))
matrix2 = rng.integers(1, 11, size = (2, 3))
print(matrix1)
print(matrix2)
matrix3 = np.dot(matrix1, matrix2)
print(matrix3)

[[3 6]
 [3 9]]
[[9 1 3]
 [3 4 8]]
[[45 27 57]
 [54 39 81]]


*8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.*

In [ ]:
rng = np.random.default_rng()
# Создание матрицы 3x3 с случайными целыми числами от 1 до 10
random_matrix = rng.integers(1, 11, size=(3, 3))
random_matrix_inv = np.linalg.inv(random_matrix)
print("Матрица:")
print(random_matrix)
print("Обратная матриця:")
print(random_matrix_inv)

Матриця:
[[ 9  1  8]
 [ 7  5  4]
 [10 10  5]]
Обернена матриця:
[[-0.5         2.5        -1.2       ]
 [ 0.16666667 -1.16666667  0.66666667]
 [ 0.66666667 -2.66666667  1.26666667]]


*9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.*

In [ ]:
rng = np.random.default_rng()
random_matrix = rng.random((4, 4))
print("Транспонованная матрица:")
print(random_matrix.T)

Транспонована матриця:
[[0.99029461 0.4644398  0.12854492 0.86370194]
 [0.21551928 0.99829288 0.21791875 0.05958516]
 [0.43378986 0.33561302 0.12442732 0.00541422]
 [0.48345504 0.17852373 0.03747564 0.61789809]]


*10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.*

In [ ]:
rng = np.random.default_rng()

new_matrix = rng.integers(1, 11, size = (3, 4))
print("Создана матрица:")
print(new_matrix)
new_vector = rng.integers(1, 11, size = 4)
print("Создан вектор:")
print(new_vector)
result = np.dot(new_matrix, new_vector)
print("Результат умножения:")
print(result)

Створена матриця:
[[ 3  8  7  2]
 [ 1  8 10  3]
 [ 8  4  3  3]]
Створен вектор:
[10 10  3  4]
Результат умножения:
[139 132 141]


*11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.*

In [ ]:
rng = np.random.default_rng()
matrix = rng.random(size = (2, 3))
print("Создана матрица:")
print(matrix)
vector = rng.random(size = 3)
print("Создан вектор:")
print(vector)
result = np.dot(matrix, vector)
print("Результат умножения:")
print(result)

Создана матрица:
[[0.70535172 0.40135376 0.98177755]
 [0.01510862 0.90250579 0.81751571]]
Создан вектор:
[0.90693507 0.02323954 0.98465784]
Результат умножения:
[1.61575045 0.8396496 ]


*12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.*

In [ ]:
rng = np.random.default_rng()
matrix1  = rng.integers(1, 11, size = (2, 2))
print("Создана матрица 1:")
print(matrix1)
matrix2 = rng.integers(1, 11, size = (2, 2))
print("Создана матрица 2:")
print(matrix2)
result = matrix1 * matrix2
print("Результат умножения:")
print(result)


Создана матрица 1:
[[ 2 10]
 [ 2  7]]
Создана матрица 2:
[[ 6  9]
 [10  8]]
Результат умножения:
[[12 90]
 [20 56]]


*13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.*

In [ ]:
rng = np.random.default_rng()
matrix1 = rng.integers(1, 11, size = (2, 2))
print("Создана матрица 1:")
print(matrix1)
matrix2 = rng.integers(1, 11, size = (2, 2))
print("Создана матрица 2:")
print(matrix2)
product_matrix = np.dot(matrix1, matrix2)
print("Результат умножения:")
print(product_matrix)


Создана матрица 1:
[[10  6]
 [ 3  2]]
Создана матрица 2:
[[2 7]
 [4 8]]
Результат умножения:
[[ 44 118]
 [ 14  37]]


*14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.*

In [ ]:
rng = np.random.default_rng()
matrix = rng.integers(1, 101, size=(5, 5))
print("Создана матрица:")
print(matrix)
total_sum = np.sum(matrix)
print("Сума елементів матриці:", total_sum)

Создана матрица:
[[ 99  64  82  13  35]
 [ 35  40  42  11  76]
 [ 42 100  64   6  14]
 [ 78  79  60  35  31]
 [ 92  63   9  28  59]]
Сума елементів матриці: 1257


*15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.*

In [ ]:
rng = np.random.default_rng()
matrix1 = rng.integers(1, 11, size = (4, 4))
print("Создана матрица 1:")
print(matrix1)
matrix2 = rng.integers(1, 11, size = (4, 4))
print("Создана матрица 2:")
print(matrix2)
result = matrix1 - matrix2
print("Результат отнимания:")
print(result)



Создана матрица 1:
[[10  3  4  3]
 [ 9  6  5 10]
 [ 7  7  8  1]
 [ 9 10  2  7]]
Создана матрица 2:
[[ 2 10  8  8]
 [ 5  3  7  1]
 [ 1  1  8  5]
 [ 1  8  2 10]]
Результат отнимания:
[[ 8 -7 -4 -5]
 [ 4  3 -2  9]
 [ 6  6  0 -4]
 [ 8  2  0 -3]]


*16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.*

In [10]:
rng =  np.random.default_rng()
matrix = rng.random(size = (3,3))
print("Создана матрица:")
print(matrix)
row_sums = np.sum(matrix, axis = 1)
print("Вектор-стовпчик сум елементів кожного рядка:")
print(row_sums.reshape(-1, 1))

Создана матрица:
[[0.05839308 0.53909702 0.79240524]
 [0.69569408 0.00914331 0.19207517]
 [0.01347572 0.45686829 0.29935315]]
Вектор-стовпчик сум елементів кожного рядка:
[[1.38989535]
 [0.89691256]
 [0.76969715]]


*17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.*

In [13]:
rng = np.random.default_rng()

matrix1 = rng.integers(1, 100, size=(3, 4))
print("Создана матрица:")
print(matrix1)

squared_matrix = matrix1**2
print("Матрица с квадратами кода:")
print(squared_matrix)

Создана матрица:
[[12 40 22 66]
 [32 99 79 91]
 [79 30 13 64]]
Матрица с квадратами кода:
[[ 144 1600  484 4356]
 [1024 9801 6241 8281]
 [6241  900  169 4096]]


*18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.*

In [16]:
rng = np.random.default_rng()

vector1 = rng.integers(1, 51, size=4)
print("Создан вектор:")
print(vector1)

sqrt_vector = np.sqrt(vector1)
print("Вектор с квадратними корнями:")
print(sqrt_vector)

Создан вектор:
[ 2 25 21  5]
Вектор с квадратними корнями:
[1.41421356 5.         4.58257569 2.23606798]
